// Generated by CoffeeScript 1.6.3
(function() {
  var data, fetch, fs, path, pending, request, util, _;

  request = require('request');

  fs = require('graceful-fs');

  path = require('path');

  util = require('util');

  _ = require('underscore');

  data = [];

  pending = 0;

  fetch = function(cmcontinue) {
    if (cmcontinue == null) {
      cmcontinue = '';
    }
    return request({
      url: "http://yugioh.wikia.com/api.php?action=query&list=categorymembers&cmtitle=Category:Card_Names&cmlimit=500&cmcontinue=" + cmcontinue + "&format=json",
      json: true
    }, function(error, response, body) {
      if (body['query-continue']) {
        fetch(body['query-continue'].categorymembers.cmcontinue);
      }
      return _.each(body.query.categorymembers, function(item) {
        var card;
        card = item.title.slice(11);
        return request({
          url: "http://yugioh.wikia.com/api.php?action=parse&prop=wikitext&page=" + (encodeURIComponent(card)) + "&format=json",
          json: true
        }, function(error, response, body) {
          var card_info, line, lineitem, matched, _i, _len, _ref;
          body.parse.wikitext['*'];
          matched = body.parse.wikitext['*'].match(/\{\{CardTable2\n\|([\s\S]*)\n\}\}/);
          card_info = {
            title: body.parse.title
          };
          _ref = matched[1].split("\n|");
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            line = _ref[_i];
            lineitem = line.replace(/\<\!\-\-.*\-\-\>/g, '').split(/\ \=\s/, 2);
            card_info[lineitem[0]] = lineitem[1];
          }
          if (card_info.image) {
            pending++;
            return request({
              url: "http://yugioh.wikia.com/api.php?action=query&prop=imageinfo&iiprop=url&titles=File:" + (encodeURIComponent(card_info.image)) + "&format=json",
              json: true
            }, function(error, response, body) {
              var file, wikia_image, _j, _len1;
              card_info['image'] = _.values(body.query.pages)[0].imageinfo[0].url;
              card_info['image_basename'] = decodeURIComponent(path.basename(card_info['image']));
              data.push(card_info);
              file = "images_wikia/" + card_info.image_basename;
              fs.stat(file, function(error, data) {
                if (data && data.size) {
                  return console.log("[SKIPPED] " + card_info.title);
                } else {
                  console.log("[GET] " + card_info.title);
                  return request(card_info.image).pipe(fs.createWriteStream(file));
                }
              });
              pending--;
              if (!pending) {
                fs.writeFile('wikia.json', JSON.stringify(data, null, 2));
                wikia_image = {};
                for (_j = 0, _len1 = data.length; _j < _len1; _j++) {
                  card = data[_j];
                  if (card.number) {
                    wikia_image[parseInt(card.number)] = card.image_basename;
                  }
                }
                fs.writeFile('images_wikia.json', JSON.stringify(wikia_image, null, 2));
                return console.log("all cards loaded");
              }
            });
          }
        });
      });
    });
  };

  fs.exists('images_wikia', function(exists) {
    if (!exists) {
      fs.mkdir('images_wikia');
    }
    return fetch();
  });

}).call(this);

/*
//@ sourceMappingURL=spider-wikia.map
*/
